"""empty message

Revision ID: 5cf04cb40418
Revises: 
Create Date: 2025-09-05 14:18:01.113613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cf04cb40418'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_access_logs_ip_address'))
        batch_op.drop_index(batch_op.f('idx_access_logs_journal_id'))
        batch_op.drop_index(batch_op.f('idx_access_logs_timestamp'))
        batch_op.drop_index(batch_op.f('idx_access_logs_user_id'))
        batch_op.create_index(batch_op.f('ix_access_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_constraint(batch_op.f('access_logs_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('access_logs_proxy_config_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('access_logs_journal_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'proxy_configs', ['proxy_config_id'], ['id'])
        batch_op.create_foreign_key(None, 'journals', ['journal_id'], ['id'])

    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_journals_access_level'))
        batch_op.drop_index(batch_op.f('idx_journals_is_active'))
        batch_op.drop_index(batch_op.f('idx_journals_proxy_path'))
        batch_op.drop_index(batch_op.f('idx_journals_slug'))
        batch_op.drop_constraint(batch_op.f('journals_proxy_path_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('journals_slug_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_journals_proxy_path'), ['proxy_path'], unique=True)
        batch_op.create_index(batch_op.f('ix_journals_slug'), ['slug'], unique=True)

    with op.batch_alter_table('proxy_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_proxy_configs_expires_at'))
        batch_op.drop_index(batch_op.f('idx_proxy_configs_is_active'))
        batch_op.drop_index(batch_op.f('idx_proxy_configs_journal_id'))
        batch_op.drop_index(batch_op.f('idx_proxy_configs_user_id'))
        batch_op.drop_constraint(batch_op.f('proxy_configs_journal_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('proxy_configs_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'journals', ['journal_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_is_active'))
        batch_op.drop_index(batch_op.f('idx_users_username'))
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_users_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)

    with op.batch_alter_table('proxy_configs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('proxy_configs_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('proxy_configs_journal_id_fkey'), 'journals', ['journal_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_proxy_configs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_proxy_configs_journal_id'), ['journal_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_proxy_configs_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_proxy_configs_expires_at'), ['expires_at'], unique=False)

    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journals_slug'))
        batch_op.drop_index(batch_op.f('ix_journals_proxy_path'))
        batch_op.create_unique_constraint(batch_op.f('journals_slug_key'), ['slug'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('journals_proxy_path_key'), ['proxy_path'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_journals_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('idx_journals_proxy_path'), ['proxy_path'], unique=False)
        batch_op.create_index(batch_op.f('idx_journals_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('idx_journals_access_level'), ['access_level'], unique=False)

    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('access_logs_journal_id_fkey'), 'journals', ['journal_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('access_logs_proxy_config_id_fkey'), 'proxy_configs', ['proxy_config_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('access_logs_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_access_logs_timestamp'))
        batch_op.create_index(batch_op.f('idx_access_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_access_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('idx_access_logs_journal_id'), ['journal_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_access_logs_ip_address'), ['ip_address'], unique=False)

    # ### end Alembic commands ###
