"""Add analytics_logs table

Revision ID: ebcc8bedd4f9
Revises: 5cf04cb40418
Create Date: 2025-09-08 19:54:45.515688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebcc8bedd4f9'
down_revision = '5cf04cb40418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_identifier', sa.String(length=255), nullable=True),
    sa.Column('account_status', sa.String(length=50), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('academic_unit', sa.String(length=255), nullable=True),
    sa.Column('user_status', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('resource_name', sa.String(length=500), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_provider', sa.String(length=255), nullable=True),
    sa.Column('resource_url', sa.String(length=1000), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('auth_success', sa.Boolean(), nullable=True),
    sa.Column('auth_failure_reason', sa.String(length=255), nullable=True),
    sa.Column('identity_provider', sa.String(length=100), nullable=True),
    sa.Column('auth_method', sa.String(length=50), nullable=True),
    sa.Column('access_timestamp', sa.DateTime(), nullable=True),
    sa.Column('access_duration', sa.Integer(), nullable=True),
    sa.Column('page_views', sa.Integer(), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=True),
    sa.Column('searches', sa.Integer(), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('request_query', sa.String(length=1000), nullable=True),
    sa.Column('user_agent', sa.String(length=1000), nullable=True),
    sa.Column('referer', sa.String(length=1000), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_size', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('custom_attributes', sa.Text(), nullable=True),
    sa.Column('access_denied', sa.Boolean(), nullable=True),
    sa.Column('denial_reason', sa.String(length=255), nullable=True),
    sa.Column('license_restriction', sa.Boolean(), nullable=True),
    sa.Column('report_period', sa.String(length=20), nullable=True),
    sa.Column('report_category', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_logs_access_timestamp'), ['access_timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_logs_access_timestamp'))

    op.drop_table('analytics_logs')
    # ### end Alembic commands ###
